build:
  script:
  - git submodule init
  - git submodule update
  - ./compile.sh
  after_script:
  - cd /media/storage/gitlab/
  - sudo rm -rf Web_Controlled_Relay
  - git clone http://git.home.lan/root/Web_Controlled_Relay.git
  - cd Web_Controlled_Relay
  - git submodule init
  - git submodule update
